// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) (OrderItem, error)
	BanUser(ctx context.Context, id uuid.UUID) (User, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	FilterProductsByCategory(ctx context.Context, arg FilterProductsByCategoryParams) ([]Product, error)
	FilterProductsByPrice(ctx context.Context, arg FilterProductsByPriceParams) ([]Product, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	GetOrderStatistics(ctx context.Context, arg GetOrderStatisticsParams) (GetOrderStatisticsRow, error)
	GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]Order, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductsByShopID(ctx context.Context, arg GetProductsByShopIDParams) ([]Product, error)
	GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error)
	GetShopsByUserID(ctx context.Context, userID uuid.UUID) ([]Shop, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListShops(ctx context.Context, arg ListShopsParams) ([]Shop, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchShops(ctx context.Context, arg SearchShopsParams) ([]Shop, error)
	UnbanUser(ctx context.Context, id uuid.UUID) (User, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateShop(ctx context.Context, arg UpdateShopParams) (Shop, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
